[package]
name = "extendr-macros"
version = "0.1.11"
authors = ["andy-thomason <andy@andythomason.com>"]
edition = "2018"
description = "Generate bindings from R to Rust."
license = "MIT"
documentation = "https://extendr.github.io/extendr/extendr_macros/index.html"
repository = "https://github.com/extendr/extendr"

[lib]
proc_macro = true

[dependencies]
syn = { version = "1.0.22", features = ["full", "extra-traits"] }
quote = "1.0.6"
lazy_static = "1.4.0"

[features]
default = []

# All features needed for testing
tests-all = ["ndarray", "libR-sys/use-bindgen"]
