name: Tests

on: [push]

jobs:
  test:
    name: Run tests (Linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
      - name: Install dependencie
        run: sudo apt-get install r-base-dev llvm-3.9-dev libclang-3.9-dev
      - name: Build
        run: cargo build
        env:
          LIBCLANG_PATH: /usr/lib/llvm-3.9/lib
      - name: Run tests
        run: cargo test -- --nocapture --test-threads=1
        env:
          LIBCLANG_PATH: /usr/lib/llvm-3.9/lib
